language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install .
  - pip install -r test-requirements.txt

script:
  - python -m pytest tests

notifications:
  email: false
  slack: prevlab:duJn4BAET8sPRW9wpKVpnY97